version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - test_db
    env_file:
      - .env
    volumes:
      - .:/myapp
    command: rails s -b 0.0.0.0
  
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: root123
  
  test_db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: test123